server:
  port: ${PORT:5000}
  servlet:
    context-path: /api
jwt:
  lifetime: 10m
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/App_db
    username: "postgres"
    password: "ivan2004"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog.yaml
