server:
  port: ${PORT:5000}
  servlet:
    context-path: /api
jwt:
  lifetime: 10m
spring:
  datasource:
    url: jdbc:h2:./Dev_db
    username: 'sa'
    password:
    h2:
      console:
        enabled: true
        path: /h2console/
        settings:
          web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true